* iced-dialog - some basic dialogs on ice

** Status: on hold

This library works for a single dialog, but fails with an error if one tries to
use more than one dialog:

#+begin_src 
`thread 'main' panicked at 'Creating EventLoop multiple times is not supported.`
#+end_src

These are related issues

- iced: Multi-window support -  https://github.com/iced-rs/iced/issues/27
- winit: Can't create event loop ondemand -  https://github.com/rust-windowing/winit/issues/2431

Work on the last item has been merged into winit 0.29.0, but iced is yet to pick
this new release up, so this project in on hold until the situation is resolved.


** Why

I would like to have GUI dialogs in ludusavi for alerts and confirmation which
can be easily "navigated" even with the gamepad controls on a Steam Deck.

As of 2023-12 I don't know of any library which does that, so this project is my
attempt.

Time will show if this works out or not.

Feedback welcome!

** Attributions

All icons used are taken from the great [[https://tabler-icons.io][tabler icons project]]: A set of over 4800
free MIT-licensed high-quality SVG icons for you to use in your web projects.

Used icons:

- alert-square-rounded
- info-square-rounded
- playstation-circle
- playstation-square
- playstation-triangle
- playstation-x
- xbox-a
- xbox-b
- xbox-x
- xbox-y
  
** License

To fit into the rust ecosystem, this project is dual licensed as:

- [[file:LICENSE-APACHE][Apache License (Version 2.0)]] 
- [[file:LICENSE-MIT][MIT License]]
